### ISSUE TITLE
ValueError: matrix G is not positive definite

### ISSUE THREAD

**Issue by shagunsodhani** [facebookresearch/GradientEpisodicMemory#2]
Hey team

Thank you so much for releasing the code for your paper. It is very useful. I have facing one problem with the code. 

I am training my code using a series of tasks. The code works fine for initial tasks but once in a while it would crash with the following error:

```
v = quadprog.solve_qp(P, q, G, h)[0]
File "quadprog/quadprog.pyx", line 104, in quadprog.solve_qp
ValueError: matrix G is not positive definite
```

I could think of one reason why this could happen - Lets say that the gradient corresponding to the current task is in a direction completely opposite to that of the gradient corresponding to the ith previous task. In this case, when we take the projection, of the current gradient with respect to the episodic gradient, the projection turns out to be a non positive-definite matrix (in the extreme case, the projection turns out to be exactly a zero vector).

Do you know of any other reasons why this might happen or if I could get around this problem by tweaking some hyperparams.

**Comment by lopezpaz** [comment]
@shagunsodhani: for regularization, try adding "the identity matrix times a small constant" to G.

**Comment by shagunsodhani** [comment]
@lopezpaz Thanks for the suggestion. I would get back to you after trying this modification. It might take some time as the error comes up once the model has been trained on a large number of tasks. I will update the result with this modification here.

**Comment by shagunsodhani** [comment]
So far there hasn't been any problem so I will close the issue. Thank you once again @lopezpaz

**Comment by andreamad8** [comment]
Thanks for your great work and for releasing these code.

I am having the same problem. As suggest I have done the following: 

` G = np.eye(t) + np.eye(t)*0.00001`

But still, I am having the same error:
`
v = quadprog.solve_qp(P, q, G, h)[0]
File "quadprog/quadprog.pyx", line 104, in quadprog.solve_qp
ValueError: matrix G is not positive definite
`

Any suggestion? @lopezpaz @shagunsodhani

**Comment by lopezpaz** [comment]
The matrix `G` that `quadprog.solve_qp` is complaining about is actually [its first argument](https://github.com/rmcgibbo/quadprog/blob/master/quadprog/quadprog.pyx#L12). Therefore, we need to change the line:

`P = 0.5 * (P + P.transpose())`

to

`P = 0.5 * (P + P.transpose()) + torch.eye(P.size(0)).mul_(1e-3)`.

**Comment by lopezpaz** [comment]
Quadprog is complaining about the positive definiteness of its first argument. The issue should be fixed by [this commit](https://github.com/facebookresearch/GradientEpisodicMemory/commit/34c6b8e9a0607db7567301c48b727430d20bee7e#diff-cec6a2b32dfeb42d70d0c5c1aaf83487R84).

**Comment by andreamad8** [comment]
Thanks. 

Andrea
