### ISSUE TITLE
Unable to run the code

### ISSUE THREAD

**Issue by gravity1989** [facebookresearch/GradientEpisodicMemory#3]
Hi,

While trying to replicate the ICARL code, the following line throws an issue. 
https://github.com/facebookresearch/GradientEpisodicMemory/blob/master/model/icarl.py#L141

The dictionary self.mem_class_x is a dictionary with keys being tensors while it is accessed through integers.
This leads to a keyerror issue.

Can you suggest something?

**Comment by lopezpaz** [comment]
Could you try replacing [this line](https://github.com/facebookresearch/GradientEpisodicMemory/blob/master/model/icarl.py#L206) with `self.mem_class_x[lab.item()] = exemplars.clone()`?
