### ISSUE TITLE
ValueError: matrix G is not positive definite

### ISSUE THREAD

**Issue by andreamad8** [facebookresearch/GradientEpisodicMemory#4]
Thanks for your great work and for releasing these code.

I am having the same problem. As suggested I have done the following:

G = np.eye(t) + np.eye(t)*0.00001

But still, I am having the same error:
v = quadprog.solve_qp(P, q, G, h)[0] File "quadprog/quadprog.pyx", line 104, in quadprog.solve_qp ValueError: matrix G is not positive definite

Any suggestion?

**Comment by lopezpaz** [comment]
Please see [this comment](https://github.com/facebookresearch/GradientEpisodicMemory/issues/2#issuecomment-431826393).
